### Board Comment Free Get

GET {{host}}/Board/Comment/Free/5f775d8d4a0ec52d9c539e9b

### Board Comment Free Create

POST {{host}}/Board/Comment/Free/5f775d8d4a0ec52d9c539e9b
Content-Type: application/json

{
  "Author": "elky",
  "Content": "댓글"
}

### Board Comment Free Create Reply Comment

POST {{host}}/Board/Comment/Free/5f775d8d4a0ec52d9c539e9b
Content-Type: application/json

{
  "OriginCommentId": "5f775f2bc71938f7a3b45cd6",
  "Author": "elky",
  "Content": "대댓글"
}

### Board Comment Free Update

PUT {{host}}/Board/Comment/Free/5f775d8d4a0ec52d9c539e9b
Content-Type: application/json

{
  "Author": "elky",
  "Content": "댓글 갱신",
}

### Board Comment Free Recommend

POST {{host}}/Board/Comment/Free/5f775f33c71938f7a3b45cd8/Recommend

### Board Comment Free NotRecommend

POST {{host}}/Board/Comment/Free/5f775f33c71938f7a3b45cd8/NotRecommend
