set DOCKER_REGISTRY=%1
set VERSION=%2
set SERVICE=%3
set WORKSPACE=%4

docker build -t %DOCKER_REGISTRY%/%SERVICE%:%VERSION% -f %SERVICE%/Dockerfile %WORKSPACE%
docker push %DOCKER_REGISTRY%/%SERVICE%:%VERSION%
